In [0]:
import numpy.matlib 
import numpy as np 
import math as m

In [0]:
#Problem 6.4

#a)

B_a = 0.25*np.array([[-1,0,2,0,-1,0],[0,-2,0,0,0,2],[-2,-1,0,2,2,-1]])
D = 30e6/(1-0.25**2)*np.array([[1,0.25,0],[0.25,1,0],[0,0,.375]])
d = np.array([0,0.0025, 0.0012, 0,0,0.0025]).reshape(6,1)

a_stress = np.mat(D)*(np.mat(B_a)*np.mat(d))
print('a) stress =\n', a_stress)


# b)
B_b = (1/1.2)*np.array([[-1,0,1,0,0,0],[0,-1.2,0,0,0,1.2],[-1.2,-1,0,1,1.2,0]])

b_stress =np.mat(D)*(np.mat(B_b)*np.mat(d))
print('b) stress =\n', b_stress)


#c)
B_c = 0.5*np.array([[-1,0,1,0,0,0],[0,-2,0,0,0,2],[-2,-1,0,1,2,0]])

c_stress =np.mat(D)*(np.mat(B_c)*np.mat(d))
print('b) stress =\n', c_stress)


a) stress =
 [[ 19200.]
 [  4800.]
 [-15000.]]
b) stress =
 [[ 32000.]
 [  8000.]
 [-25000.]]
b) stress =
 [[ 19200.]
 [  4800.]
 [-15000.]]


matrix([[ 0.0006 ],
        [ 0.     ],
        [-0.00125]])

In [0]:
# Problem 6.13\

B1 = (1/200)*np.array([[0,0,10,0,-10,0],[0,-20,0,0,0,20],[-20,0,0,10,20,-10]])
B2 = (1/200)*np.array([[-10,0,10,0,0,0],[0,0,0,-20,0,20],[0,-10,-20,10,20,0]])
D = (30e6/(1-0.3**2))*np.array([[1,0.3,0],[0.3,1,0],[0,0,0.35]])

A = 100
t = 1

K1 = t*A*(np.mat(np.transpose(B1))*np.mat(D))*np.mat(B1)
K2 = t*A*np.mat(np.transpose(B2))*np.mat(D)*np.mat(B2)

print('K1 = \n',K1*(0.91/375e3))
print('K2 = \n',K2*(0.91/375e3))


K_simplified = (375e3/0.91)*np.array([[48,0,-28,14],[0,87,12,-80],[-28,12,48,-26],[14,-80,-26,87]])
F = np.array([[0],[-5000],[0],[-5000]])

disp = np.mat(np.linalg.inv(K_simplified))*np.mat(F)

print('\nnodal displacement = \n',disp)

disp3 = np.array([0,0,disp[0],disp[1],0,0]).reshape(6,1)

stress3 = np.mat(D)*(np.mat(B1)*np.mat(disp3))
print('\nstress3 =\n', stress3)

p_stress3 = np.array([(824+247)/2 + m.sqrt(((824-247)/2)**2 + (-1587.7)**2),(824+247)/2 - m.sqrt(((824-247)/2)**2 + (-1587.7)**2)])
print('\nprincipal stress3 = ',p_stress3)

p_angle3 = 0.5*m.atan((2*-1587.7)/(824.7-247.4))
print("principal angle3 =", m.degrees(p_angle3))

disp34 = np.array([[0],[0],disp[2],disp[3],disp[0],disp[1]])


stress34 = np.mat(D)*(np.mat(B2)*np.mat(disp34))
print('\nstress34 =\n', stress34)

p_stress34 = np.array([(-825+294)/2 + m.sqrt(((-825-294)/2)**2 + (-412.3)**2),(-825+294)/2 - m.sqrt(((-825-294)/2)**2 + (-412.3)**2)])
print('\nprincipal stress34 = ',p_stress34)

p_angle34 = 0.5*m.atan((2*-412.3)/(-824.7-293.8))
print("principal angle34 =", m.degrees(p_angle34))

K1 = 
 [[ 28.   0.   0. -14. -28.  14.]
 [  0.  80. -12.   0.  12. -80.]
 [  0. -12.  20.   0. -20.  12.]
 [-14.   0.   0.   7.  14.  -7.]
 [-28.  12. -20.  14.  48. -26.]
 [ 14. -80.  12.  -7. -26.  87.]]
K2 = 
 [[ 20.   0. -20.  12.   0. -12.]
 [  0.   7.  14.  -7. -14.   0.]
 [-20.  14.  48. -26. -28.  12.]
 [ 12.  -7. -26.  87.  14. -80.]
 [  0. -14. -28.  14.  28.   0.]
 [-12.   0.  12. -80.   0.  80.]]

nodal displacement = 
 [[ 0.00050029]
 [-0.00275196]
 [-0.00060854]
 [-0.00293237]]

stress3 =
 [[matrix([[824.65972778]])]
 [matrix([[247.39791833]])]
 [matrix([[-1587.67013611]])]]

principal stress3 =  [ 2149.19871413 -1078.19871413]
principal angle3 = -39.847973726732086

stress34 =
 [[-824.6597277822257]
 [293.8350680544451]
 [-412.32986389111227]]

principal stress34 =  [ 429.50470502 -960.50470502]
principal angle34 = 18.199513479647727
